language: node_js
cache: yarn
node_js:
- '13'
script:
- yarn build
- yarn test
deploy:
  skip_cleanup: true
  provider: npm
  email: rpbiwer@gmail.com
  on:
    tags: true
    branch: master
  api_key:
    secure: oHF/hRALx1gJV1TFgBLAqrWqqWt/fVOiRbQQK7KxS7/IBPQ6KzLi+UTS7y94yFVybDm9OGZwrOxGhYy3dAg9SOJYcxWC5hAi1ikY/M4CgaT2k8CWoL5n+iI9LDoEXLKzXKL6efAxgGQ/9bNGi0MRnbuFCEZDC6Oe8A5ZWOE4yf6R4Sjh4+5xtvHZnqo4FBIhtPQYZ0MrRhWvTKKaljhPrpWR3wrLL9UHttO2k/HpYw1qrmhJoAKiXgs6LBlWMNPcCoysVee1bYyZlNuvwlXM4R7NaP8h4XH/dOXttrZVH1hy8fopsEnv4BzcYnf6g/o5QqD0U8h2qgnI7xGKMTOBu1cFQA/JlKUDscsQ0n4mbjb5Py6VyWxTol9EKl4DRPzk9z/EQVJ0jqjLbZfs/ETWbzXo7tocAYQ47LOp/4pV6JeovuOun6rHImTGGjk+8oEqiNUMkpyo8BYynequt1C/n7Na/EkGlCdynNstjUdvaT/9SJ+yXjazBMGhXHlDHaZXjxuxCffV/SMsx1yKspBJsCo5QGdRb4y0elN8jtqihTR3E4IEk9DHGP4qE86irhXSfLe0JVdSEknxzYDwmfhfVNdFWRWBKkKqHgJjUOpG+fbjiSB3Lo+f4AeHnlcFdk2zEbQQE1sEES/fABWk/BTfCEEq2pPlgB/wyAVPCTKCCnc=
