language: node_js
cache: yarn
node_js:
- '13'
script:
- yarn build
- yarn test
deploy:
  provider: npm
  email: rpbiwer@gmail.com
  on:
    tags: true
    branch: master
  api_key:
    secure: SZ3ZNoRKsHL3+FOlAENeMxoWE6Pe0xUtUWMw2c1HpNqabj8TW7NMFA4ZBnPlWttINx8k2BxpkT532ExNEqrLJQkgOu+5xTdbZY4joSMqF2IxuemLUnMIE5K3QicQ7MsXYRJ0bkWzskHzXThMLmdhuUT27CTp3uErNoEmYYjvKuYKlOh1Dbbgx9cs4AftN0XCf+tjERFyZhm6wmWiQPjYEuoanZDt5u4g3pmIIsdaashPpt7HlcgHNPzhyAUoClUJORJReB08akfLNT0UATQZyOPTFUC2GZIGaV8X5InU04WIysL5nX5sRxW47FPW5erBoLsOiqHPShBYM7I6tnSw1B8/Q+sZ/CckECNxOf7pRZrKv38Y1XVYeSIsz9OKitYBtS8dbWyBO2t5PLUPi+xGW+Qf0k7Dn2HpYeEY/115XU228IvthEk/vOLzS43IRLDCQLH18GQuarvc0eVQVx8kdw1apKw6ChgqUMJMzDtrLCqoeq94BBYFH5CR57xSduHm0/6qP2aZk0eCyHRdSrY01KJeBCxq76TZ7VY/ss9cyMV5L2wqGQ3+CpcpfD36RIxVwjy/ncLVBnNvbnIl7CeSHyVtQlrmCPnZRe9VAPPQisYbDBQAefbbTg6b907p/UScTkj8fHXIpNHd04kEQmR3Qj4uGP7zDJOR3e/OrmMnewc=
